# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
SLACK_CLIENT_ID: "939242411104.1241540577413"
SLACK_CLIENT_SECRET: "3296e42e7c4e2a5bc7637fb9db478e9b"
SLACK_BOT_ACCESS_TOKEN: "xoxb-939242411104-1241564899029-Eap43ZWWwZzLqfg2sqlfA1G2"
FRONTEND_URL: "https://localhost:3000/dashboard"
WATSON_URL: "https://api.us-south.personality-insights.watson.cloud.ibm.com/instances/7e9c434c-c738-42ba-b071-c6f46a117f8e"
WATSON_API_KEY: "9BXlbUAFvkYUOXGvTd4mk3e_KnuzxOX3_F9rnpSoiRsH"
